<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Stephen-PC" name="com.revature.runners.LocationTestRunner" tests="9" failures="0" timestamp="31 Jan 2018 21:32:22 GMT" time="38.544" errors="1">
  <testcase name="openApplication" time="9.107" classname="com.revature.runners.LocationTestRunner"/>
  <testcase name="testLoginMethod" time="3.099" classname="com.revature.runners.LocationTestRunner"/>
  <testcase name="editBuilding" time="25.849" classname="com.revature.runners.LocationTestRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.revature.runners.LocationTestRunner.editBuilding(LocationTestRunner.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- editBuilding -->
  <testcase name="closeApplication" time="0.489" classname="com.revature.runners.LocationTestRunner"/>
  <testcase name="addBuilding" classname="com.revature.runners.LocationTestRunner">
    <skipped/>
  </testcase> <!-- addBuilding -->
  <testcase name="addLocation" classname="com.revature.runners.LocationTestRunner">
    <skipped/>
  </testcase> <!-- addLocation -->
  <testcase name="addRoom" classname="com.revature.runners.LocationTestRunner">
    <skipped/>
  </testcase> <!-- addRoom -->
  <testcase name="editRoom" classname="com.revature.runners.LocationTestRunner">
    <skipped/>
  </testcase> <!-- editRoom -->
  <testcase name="editLocation" classname="com.revature.runners.LocationTestRunner">
    <skipped/>
  </testcase> <!-- editLocation -->
</testsuite> <!-- com.revature.runners.LocationTestRunner -->
