<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Stephen-PC" name="com.revature.runners.ProfileTestRunner" tests="8" failures="0" timestamp="01 Feb 2018 23:45:25 GMT" time="39.534" errors="1">
  <testcase name="openApplication" time="9.339" classname="com.revature.runners.ProfileTestRunner"/>
  <testcase name="testLoginMethod" time="8.223" classname="com.revature.runners.ProfileTestRunner"/>
  <testcase name="selectSkill" time="8.608" classname="com.revature.runners.ProfileTestRunner"/>
  <testcase name="removeSkill" time="6.403" classname="com.revature.runners.ProfileTestRunner"/>
  <testcase name="saveSkills" time="4.431" classname="com.revature.runners.ProfileTestRunner"/>
  <testcase name="closeApplication" time="0.467" classname="com.revature.runners.ProfileTestRunner"/>
  <testcase name="removeCertification" time="2.063" classname="com.revature.runners.ProfileTestRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.revature.runners.ProfileTestRunner.removeCertification(ProfileTestRunner.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- removeCertification -->
  <testcase name="addCertification" classname="com.revature.runners.ProfileTestRunner">
    <skipped/>
  </testcase> <!-- addCertification -->
</testsuite> <!-- com.revature.runners.ProfileTestRunner -->
